services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_CACHE_TYPE=redis
      - SPRING_DATASOURCE_READ_URL=jdbc:postgresql://db:5432/shorturl
      - SPRING_DATASOURCE_READ_USERNAME=postgres
      - SPRING_DATASOURCE_READ_PASSWORD=password
      - SPRING_DATASOURCE_WRITE_URL=jdbc:postgresql://db:5432/shorturl
      - SPRING_DATASOURCE_WRITE_USERNAME=postgres
      - SPRING_DATASOURCE_WRITE_PASSWORD=password
    depends_on:
      - redis
      - db
    networks:
      - redis-app-net
      - db-net
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shorturl
    ports:
      - "5432:5432"
    networks:
      - db-net
  redis:
    image: "redis/redis-stack"
    container_name: "redis-stack"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    entrypoint: >
      redis-server
        --appendonly no
        --protected-mode no
        --maxmemory 500mb
        --maxmemory-policy allkeys-lfu
    networks:
      - redis-app-net
networks:
  db-net:
    driver: bridge
  redis-app-net:
    driver: bridge